### ISSUE TITLE
R5: are the authors unknown to wru known in distribution?

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity-manuscript#70]
> Of 34,050 corresponding authors, over 25% (8,770) had a last name for which wru did not provide predictions.  Do the author know if these were random or non-random in distribution.

**Comment by trangdata** [comment]
These missing values were non-random. Because wru uses the US census to make predictions, many of the missing predictions are on names not observed in the US census. Therefore, we expect an underestimation of the number of these names in both the list of authors and honorees.

I can open a PR to add some limitations including this one.
